version: "3.9"

services:

  postgres:
    image: postgres:11-alpine3.16
    container_name: webstore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - webstore-postgres:/var/lib/postgresql/data
      - init.sql:/data/application/init.sql

  webstore:
    build:
      context: .
    container_name: webstore-app
    volumes:
      - ./webstore:/opt/app
    links:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  webstore-postgres: